export const gatewayAbi = [
  {
    inputs: [
      {internalType: 'address', name: '_weth', type: 'address'},
      {internalType: 'address', name: '_factory', type: 'address'},
      {internalType: 'address', name: '_feeTo', type: 'address'},
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [{internalType: 'address', name: 'owner', type: 'address'}],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [{internalType: 'address', name: 'account', type: 'address'}],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'wallet', type: 'address'},
      {indexed: true, internalType: 'address', name: 'token', type: 'address'},
      {indexed: false, internalType: 'uint256', name: 'tknAmount', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'ethAmount', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'tknReserve', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'ethReserve', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'usrBalance', type: 'uint256'},
    ],
    name: 'Buy',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'wallet', type: 'address'},
      {indexed: true, internalType: 'address', name: 'token', type: 'address'},
      {indexed: false, internalType: 'uint256', name: 'tknAmount', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'ethAmount', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'tknReserve', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'ethReserve', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'usrBalance', type: 'uint256'},
    ],
    name: 'MemeCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'previousOwner', type: 'address'},
      {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'wallet', type: 'address'},
      {indexed: true, internalType: 'address', name: 'token', type: 'address'},
      {indexed: false, internalType: 'uint256', name: 'tknAmount', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'ethAmount', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'tknReserve', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'ethReserve', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'usrBalance', type: 'uint256'},
    ],
    name: 'Sell',
    type: 'event',
  },
  {
    inputs: [
      {internalType: 'address', name: 'token', type: 'address'},
      {internalType: 'uint256', name: 'tknAmount', type: 'uint256'},
      {internalType: 'uint256', name: 'ethAmount', type: 'uint256'},
      {internalType: 'uint256', name: 'maxPrice', type: 'uint256'},
      {internalType: 'uint256', name: 'deadline', type: 'uint256'},
    ],
    name: 'buy',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'string', name: 'name', type: 'string'},
      {internalType: 'string', name: 'symbol', type: 'string'},
      {internalType: 'uint256', name: 'tknAmount', type: 'uint256'},
      {internalType: 'uint256', name: 'ethAmount', type: 'uint256'},
      {internalType: 'uint256', name: 'deadline', type: 'uint256'},
    ],
    name: 'createMeme',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: '', type: 'address'},
      {internalType: 'uint256', name: '', type: 'uint256'},
    ],
    name: 'createdBy',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: '', type: 'address'}],
    name: 'creatorOf',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getFactory',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getFeeRatio',
    outputs: [{internalType: 'uint8', name: '', type: 'uint8'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getFeeTo',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'wallet', type: 'address'}],
    name: 'getMemesCreatedBy',
    outputs: [{internalType: 'address[]', name: '', type: 'address[]'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getMintFee',
    outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'token', type: 'address'},
      {internalType: 'uint256', name: 'tknAmountEst', type: 'uint256'},
      {internalType: 'uint256', name: 'ethAmountEst', type: 'uint256'},
    ],
    name: 'quoteBuy',
    outputs: [
      {internalType: 'uint256', name: 'tknAmount', type: 'uint256'},
      {internalType: 'uint256', name: 'ethAmount', type: 'uint256'},
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'token', type: 'address'},
      {internalType: 'uint256', name: 'tknAmountEst', type: 'uint256'},
      {internalType: 'uint256', name: 'ethAmountEst', type: 'uint256'},
    ],
    name: 'quoteSell',
    outputs: [
      {internalType: 'uint256', name: 'tknAmount', type: 'uint256'},
      {internalType: 'uint256', name: 'ethAmount', type: 'uint256'},
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'token', type: 'address'},
      {internalType: 'uint256', name: 'tknAmount', type: 'uint256'},
      {internalType: 'uint256', name: 'ethAmount', type: 'uint256'},
      {internalType: 'uint256', name: 'minPrice', type: 'uint256'},
      {internalType: 'uint256', name: 'deadline', type: 'uint256'},
    ],
    name: 'sell',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: '_factory', type: 'address'}],
    name: 'setFactory',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint8', name: '_feeRatio', type: 'uint8'}],
    name: 'setFeeRatio',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: '_feeTo', type: 'address'}],
    name: 'setFeeTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: '_mintFee', type: 'uint256'}],
    name: 'setMintFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'token', type: 'address'}],
    name: 'tokenSupply',
    outputs: [
      {internalType: 'uint256', name: '', type: 'uint256'},
      {internalType: 'uint8', name: '', type: 'uint8'},
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'weth',
    outputs: [{internalType: 'contract IWETH', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {stateMutability: 'payable', type: 'receive'},
] as const;
